### ISSUE TITLE
Lerna is no longer maintained

### ISSUE THREAD

**Issue by cristianbuta** [code11/engine#127]
The author reconfirmed this in a tweet earlier this week and it seems that he is not willing to pass over the ownership of the repo. 

People already started some forks as being discussed in this issue https://github.com/lerna/lerna/issues/2703.

Maybe it should be considered that the project migrates to a different monorepo management tool in the future.

**Comment by dumconstantin** [comment]
Interesting! Thank you for the heads up!

**Comment by dumconstantin** [comment]
In other news seems that Nrwl has taken over the ownership, which actually could mean a brighter future for lerna. So I'll close the issue for now as there's no immediate reason to switch to another monorepo manager.

https://github.com/lerna/lerna/issues/3121
