### ISSUE TITLE
Development for Express

### ISSUE THREAD

**Issue by dumconstantin** [code11/engine#20]
Might be an engine implementation designed for express or just a set of producers that handle requests.

TBD

**Comment by AlexandruSimandi** [comment]
partikip

**Comment by dumconstantin** [comment]
With the new Engine Modules the implementation is trivial and doesn't require further extending the Engine.

See the pattern detailed here:

https://code11.github.io/engine/docs/patterns/request-response

What we might end up providing is a sandbox with a working example.
