### ISSUE TITLE
Is Arg. really needed or should it be shorthanded?

### ISSUE THREAD

**Issue by dumconstantin** [code11/engine#24]
Is Arg.foo necessary or should we make it available as a short hand (like in the case of Prop)?

```
const a = view(( id = 'foo', bar = Get.foo[Arg.id]) => {})
```
is equivalent to:
```
const a = view(( id = 'foo', bar = Get.foo[id]) => {})
```

**Comment by astudor** [comment]
50% of current repo watchers tend to forget to put Arg in Get.foo[Arg.bar] and write directly Get.foo[bar] 
I feel that using that "Arg" syntax doesn't bring much value.

**Comment by dumconstantin** [comment]
Unfortunately there are several cases where this can come in conflict with environment variables while also creating confusion in code.

It would be best to keep things as specific as possible to avoid confusion.
